name: Testing

on: 
  pull_request:
  push:
      branches:
        - master

jobs:
  static:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing CI
        run: npm ci

      - name: Test Run
        run: npm run test:lint

  unit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing CI
        run: npm ci
        
      - name: Test Run
        run: npm run test:code
    
